[package]
name = "path2md"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
file-format = { version = "0.24.0", features = ["reader"] }
glob = "0.3.1"
justerror = "1.1.0"
thiserror = "1.0.57"
